--------------------------------------------------------
--  Fichier créé - mercredi-décembre-04-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TABMED
--------------------------------------------------------

  CREATE TABLE "ASMAA"."TABMED" 
   (	"REFMEDICAMENT" VARCHAR2(20 BYTE), 
	"NOMPRODUIT" VARCHAR2(20 BYTE), 
	"NBRMED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ASMAA.TABMED
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TABMED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASMAA"."TABMED_PK" ON "ASMAA"."TABMED" ("REFMEDICAMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TABMED
--------------------------------------------------------

  ALTER TABLE "ASMAA"."TABMED" ADD CONSTRAINT "TABMED_PK" PRIMARY KEY ("REFMEDICAMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ASMAA"."TABMED" MODIFY ("REFMEDICAMENT" NOT NULL ENABLE);
  ALTER TABLE "ASMAA"."TABMED" MODIFY ("NOMPRODUIT" NOT NULL ENABLE);
