--------------------------------------------------------
--  File created - Wednesday-December-04-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "AZERTY"."PATIENT" 
   (	"NUMP" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DRDV" VARCHAR2(20 BYTE), 
	"MALADIE" VARCHAR2(20 BYTE), 
	"OBSERVATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZERTY.PATIENT
SET DEFINE OFF;
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (34344,'YTSQD',null,null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (1412,'adsdsadas','sadsda',null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (12323,'yoooooo','dd',null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (4123,'ASD','DQS','QSD','sd','sd');
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (1,'fff','ggg','qsddsq',null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (123,'qsdds',null,null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (1244,'sqd',null,null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (4,'d',null,null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (131,'d',null,null,null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (41,'fff','ffgggg','hhh',null,null);
Insert into AZERTY.PATIENT (NUMP,NOM,PRENOM,DRDV,MALADIE,OBSERVATION) values (45445,'144444',null,null,null,null);
--------------------------------------------------------
--  DDL for Index PATIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZERTY"."PATIENT_PK" ON "AZERTY"."PATIENT" ("NUMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "AZERTY"."PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("NUMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZERTY"."PATIENT" MODIFY ("NUMP" NOT NULL ENABLE);
